### ISSUE TITLE
DatabaseInterface Fetch Mode

### ISSUE THREAD

**Issue by halPlatzke** [MakairaIO/oxid-connect#1]
When you use the Oxid Model (in any way, don't need to load the article) in an Modifier and get the Long Desciption the `AttributeModifier` from Makaira throws an exception.

`Unknown property $0 in Makaira\Connect\Type\Common\AssignedTypedAttribute`

Own Modifier
```php
public function apply(Type $type)
    {
        $objectData = array_merge((array)$type, $type->additionalData);
        $article = oxNew(Article::class);
        $article->assign($objectData);

        $type->longdesc = $article->getLongDescription()->value;
        $type->OXLONGDESC = $article->getLongDescription()->value;

        return $type;
    }
```
Problem: `getLongDescription()` internally calls `\OxidEsales\Eshop\Core\DatabaseProvider::getDb();` witch resets the Fetch Mode to numeric, DatabaseInterface does not change the fetch Mode back, but the AttributeModifier expects associative Results and can't Map nummeric Results to Class properties.

Possible Workaround:
Put `\OxidEsales\Eshop\Core\DatabaseProvider::getDb(\OxidEsales\Eshop\Core\DatabaseProvider::FETCH_MODE_ASSOC);` right before the return in own Modifier

Possible Fix:
Ensure that Fetch Mode is set to associative in `AttributeModifier` or other places

**Comment by luflow** [comment]
@halPlatzke We will address this issue in our next sprint. Just to be sure: Your OXID version is 6.2 - correct?

**Comment by luflow** [comment]
@halPlatzke Can you please provide your services.yaml for this case? Just to make it better reproducible on our machines.

**Comment by halPlatzke** [comment]
something like this should work

```yaml
services:
  makaira.connect.modifiers.product.ownModifier.title:
    class: ownNamespace/ownClass
    public: true
    tags:
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.product', priority: 10000, method: addModifier }
      - { name: 'kernel.event_listener', event: 'makaira.importer.modifier.variant', priority: 10000, method: addModifier }
```

yes oxid 6.2 (6.2.2)
